### ISSUE TITLE
mdl-button not applying mdl-button--icon class

### ISSUE THREAD

**Issue by mixedCase** [posva/vue-mdl#60] opened 2016-08-25 07:37 UTC
Title.

Example code:

```
<mdl-button icon>
    <i class="material-icons">star</i>
</mdl-button>
```

**Comment by posva** [comment] 2016-08-25 07:41
Can you provide a repro? it's working nicely on the docs

**Comment by mixedCase** [comment] 2016-08-25 07:46
Using webpack template generated with vue-cli, this is my index.html:

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<title>volta-client-web</title>
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://code.getmdl.io/1.2.0/material.indigo-amber.min.css">
		<script src="https://code.getmdl.io/1.2.0/material.min.js"></script>
	</head>
	<body>
		<app></app>
		<!-- built files will be auto injected -->
	</body>
</html>
```

App.vue:

```
<template>
	<div id="app">
		<main>
			<header class="toolbar">
				<mdl-button icon>
					<i class="material-icons">star</i>
				</mdl-button>
			</header>
			<content>
				<p>Hey</p>
			</content>
		</main>
	</div>
</template>

<script>
import Hello from './components/Hello'

export default {
	components: {
		Hello
	},
	vuex: {
	}
}
</script>

<style lang="scss">
</style>
```

and main.js:

```
import Vue from 'vue'
import VueMdl from 'vue-mdl'
import App from './App'

Vue.use(VueMdl)

/* eslint-disable no-new */
new Vue({
	el: 'body',
	components: { App }
})
```

**Comment by posva** [comment] 2016-08-25 07:51
By a repro, I mean a [jsfiddle.net](jsfiddle.net)

**Comment by mixedCase** [comment] 2016-08-25 07:58
I have no idea how to do it since I've only worked with ES6 and .vue files.

Do you have any template [like what Vue.js provides?](https://jsfiddle.net/yyx990803/okv0rgrk/)

**Comment by posva** [comment] 2016-08-25 08:13
I thought I had one, but I've lost it :(
I'll create another and add a CONTRIBUTING.md file

**Comment by posva** [comment] 2016-08-25 12:32
The documentation is actually wrong. The icon is supposed to be used with an argument:
`<mdl-button icon="star"></mdl-button>`
The funny thing is this is a duplicate of #51 😆 

In case you need a playground: https://jsfiddle.net/posva/2hr9z7xk/

Thanks for pointing it out anyway! I'll fix it this week

**Closed by posva** 2016-08-25 12:32 UTC
Labels: documentation, enhancement
