### ISSUE TITLE
v-on:click doesn't work on vue-mdl@next with vue 2.0

### ISSUE THREAD

**Issue by timeswind** [posva/vue-mdl#76] opened 2016-11-28 19:55 UTC

**Comment by posva** [comment] 2016-11-28 23:52
use the `native` modifier duplicate of #74

**Closed by posva** 2016-11-28 23:52 UTC

**Comment by timeswind** [comment] 2016-11-29 00:01
what is native modifier

**Comment by posva** [comment] 2016-11-29 09:47
https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components
