### ISSUE TITLE
Demo site crashed in iPad Safari

### ISSUE THREAD

**Issue by vu-dang** [posva/vue-mdl#18] opened 2016-03-13 14:48 UTC
The demo site does not work well in iPad Safari.  It flickers when scrolling; the drop down menu would make the page blank; and scrolling fast causes the page to crash.

Is this an issue with vue.js or the mdl library?

**Comment by posva** [comment] 2016-03-13 22:11
Hi,
It cannot be a bug with vue, that's for sure. I don't know where it can comes from.

I don't have an ipad, I can only try on an emulator so I cannot reproduce the error. As the doc was not meant to be viewed on an ipad and I cannot actually verify that a problem exist, I'm closing the issue.

Thanks for taking the time in opening the issue, I'll try to test somehow on someone else ipad and reopen the issue if necessary

**Closed by posva** 2016-03-13 22:11 UTC
