### ISSUE TITLE
mdl-menu, how to display multiple menu in a repeat list (v-for)

### ISSUE THREAD

**Issue by timeswind** [posva/vue-mdl#39] opened 2016-05-28 11:56 UTC

**Comment by posva** [comment] 2016-06-20 22:38
Sorry, I ignored this. I couldn't understand the question and forgot to ask 😓 
Can you make it clearer?

**Comment by posva** [comment] 2016-06-30 11:13
Closing because the issue is unclear 😕

**Closed by posva** 2016-06-30 11:13 UTC
